---
abstract: 'An intersection of Moose type constraints'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
generated_by: 'Dist::Zilla version 1.100600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Meta-TypeConstraint-Intersection
requires:
  ExtUtils::MakeMaker: 6.11
  Moose: 0
  MooseX::Types::Moose: 0
  Test::More: 0.88
  aliased: 0
  namespace::autoclean: 0
version: 0.03
