---
abstract: 'An intersection of Moose type constraints'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Meta-TypeConstraint-Intersection
requires:
  Moose: 0
  MooseX::Types::Moose: 0
  Test::More: 0.88
  aliased: 0
  namespace::autoclean: 0
version: 0.04
